// Turns a StudioConfig into a block of CSS variables. This single function is
// the source of truth for "what the choices mean", and is used in two places:
//   1. The Vite dev plugin writes its output to src/styles/theme.generated.css
//      (so saved choices persist with no flash on reload).
//   2. The in-browser live preview injects it into a <style> tag for instant
//      feedback while the user is still deciding.
// Pure string in / string out — safe to import from Node or the browser.

import { colorById, densityById, fontById, motionById } from "./presets"
import type { StudioConfig } from "./types"

export function buildThemeCss(config: StudioConfig): string {
  const font = fontById(config.font)
  const color = colorById(config.color)
  const density = densityById(config.density)
  const motion = motionById(config.motion)
  const radius = `${config.radius}rem`
  const scroll = config.smoothScroll ? "smooth" : "auto"

  return `/* AUTO-GENERATED by Setup Studio — edit your choices, not this file.
 * Re-run the in-app Studio or the /setup command to regenerate. */

:root {
  /* Type */
  --studio-font-heading: ${font.heading};
  --studio-font-body: ${font.body};

  /* Shape & density */
  --radius: ${radius};
  --spacing: ${density.spacing}rem;

  /* Motion (read by the <Reveal> primitive and transitions) */
  --motion-duration: ${motion.duration}ms;
  --motion-distance: ${motion.distance}px;
  --motion-ease: ${motion.ease};

  /* Accent (light) */
  --primary: ${color.light.primary};
  --primary-foreground: ${color.light.primaryForeground};
  --ring: ${color.light.ring};
  --sidebar-primary: ${color.light.primary};
  --sidebar-primary-foreground: ${color.light.primaryForeground};
  --sidebar-ring: ${color.light.ring};
}

.dark {
  /* Accent (dark) */
  --primary: ${color.dark.primary};
  --primary-foreground: ${color.dark.primaryForeground};
  --ring: ${color.dark.ring};
  --sidebar-primary: ${color.dark.primary};
  --sidebar-primary-foreground: ${color.dark.primaryForeground};
  --sidebar-ring: ${color.dark.ring};
}

html {
  scroll-behavior: ${scroll};
}
`
}
